package com.example.edgar.tpdm_u5_ejercicio_2_edgarefrenpozasbogarin;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class BaseDatos extends SQLiteOpenHelper {
    public BaseDatos(Context c){
        super(c,"respuestas",null,1);
    }

    @Override
    public void onCreate(SQLiteDatabase p1)
    {
        String c1="create table respuestas(municipio varchar,ingles varchar,español varchar)";
        p1.execSQL(c1);
        p1.execSQL("insert into respuestas values('acaponeta','Acaponeta means, \"Place next to the river where the bean grows entangled in the reed cane\"; that is achieved by combining the translation of Tepehuano Acaponeta (Caponeta) which means, \"place next to the river\"; and of the Nahuatl Acatl-pol-etl-tlan which means, \"place where the bean grows entangled in the cane reed\".','Acaponeta significa, \"Lugar junto al río donde crece el frijol enredado en la caña de carrizo\"; que se logra conjuntando la traducción del Tepehuano Acaponeta (Caponeta) que significa, \"lugar junto al río\"; y del Náhuatl Acatl-pol-etl-tlan que significa, \"lugar donde crece el frijol enredado en la caña de carrizo\". ')");
        p1.execSQL("insert into respuestas values('ahuacatlan','Ahuacatlán, is a municipality of the State of Nayarit, Mexico. It has an area of \u200B\u200B494.4 km² and is located southeast of the state, bordering the municipalities of Santa Maria del Oro to the north, San Pedro Lagunillas to the west, Jala and Ixtlán del Río to the east and Amatlán de Cañas to the southeast.\n" +
                "The municipal seat bears the same name Ahuacatlán that etymologically means \"Lugar de Aguacates\" (from the Nahuatl āhuac-avocado and -tlan place, place).','Ahuacatlán, es un municipio del Estado de Nayarit, México. Tiene una extensión de 494.4 Km² y se ubica al Sureste de la entidad, limitando con los municipios de Santa María del Oro al Norte, San Pedro Lagunillas al Oeste, Jala e Ixtlán del Río al Este y Amatlán de Cañas al Sureste.\n" +
                "La cabecera municipal lleva el mismo nombre Ahuacatlán que etimológicamente significa \"Lugar de Aguacates\" (del náhuatl āhuac- aguacate y -tlan lugar, sitio')");
        p1.execSQL("insert into respuestas values('amatlandecañas','Amatlán de Cañas, is a municipality of the State of Nayarit, Mexico. It has an area of \u200B\u200B509.77 km². It is located in the southeastern part of the entity, bordering the northwest with the municipality of Ahuacatlán, and northeast with Ixtlán del Río.','Amatlán de Cañas, es un municipio del Estado de Nayarit, México. Tiene una superficie de 509,77 km². Se ubica en la parte sureste de la entidad, limitando al noroeste con el municipio de Ahuacatlán, y al noreste con Ixtlán del Río. ')");
        p1.execSQL("insert into respuestas values('compostela','Compostela is a municipality in the Mexican state of Nayarit, its old name in the Nahuatl language was Cuatlan Valley or Place where there are snakes. The municipality of Compostela is located on the south coast of the state. It is located within the extreme geographic coordinates between the parallels 21º22 to 20º52 of north latitude; and meridians 104º49 to 105º22 west longitude','Compostela es un municipio del estado mexicano de Nayarit, su nombre antiguo en lengua náhuatl era Valle de Cuatlan o Lugar donde hay serpientes. El municipio de Compostela se localiza en la costa sur del estado. Se ubica dentro de las coordenadas geográficas extremas entre los paralelos 21º22’ a 20º52’ de latitud norte; y los meridianos 104º49’ a 105º22’ de longitud oeste')");
        p1.execSQL("insert into respuestas values('huajicori','The Municipality of Huajicori is one of the 20 municipalities in which the Mexican state of Nayarit is divided for its internal regime. It is located at the northern end of it and its municipal seat is the town of the same name.','El Municipio de Huajicori es uno de los 20 municipios en que se divide para su régimen interior el estado mexicano de Nayarit. Se encuentra localizado en el extremo norte del mismo y su cabecera municipal es el pueblo del mismo nombre.')");
        p1.execSQL("insert into respuestas values('ixtlándelrio','Ixtlán del Río is a municipality located in the southeast of the State of Nayarit. It has been called the door of our State (Nayarit), since every traveler who goes to any point of the northwest, or travels to the center of the Republic, passes through this city.','Ixtlán del Río es un municipio ubicado en el sureste del Estado de Nayarit. Se le ha denominado la puerta de nuestro Estado (Nayarit), ya que todo viajero que se encamina hacia cualquier punto del noroeste, o viaja al centro de la República, pasa por esta ciudad. ')");
        p1.execSQL("insert into respuestas values('jala','The municipality of Jala is one of the 20 municipalities in which the Mexican state of Nayarit is divided. It is located in the southeast of the state territory and its head is the town of Jala.','El municipio de Jala es uno de los 20 municipios en que se encuentra dividido el estado mexicano de Nayarit. Se encuentra localizado en el sureste del territorio estatal y su cabecera es la localidad de Jala. ')");
        p1.execSQL("insert into respuestas values('xalisco','Xalisco is a municipality of the State of Nayarit, Mexico. It has an area of \u200B\u200B290.6 km². It limits to the North with the municipality of Tepic. The municipal capitals of both municipalities are conurbated and jointly form the core of the Metropolitan Area of \u200B\u200BTepic, east and south with Santa María del Oro, south with Compostela, and; to the west with San Blas. In this town is the Technological University of Nayarit. It is located 7 km from Tepic and 739 km from the capital of the country, Mexico City.','Xalisco es un municipio del Estado de Nayarit, México. Tiene una superficie de 290,6 km². Limita al Norte con el municipio de Tepic. Las cabeceras municipales de ambos municipios están conurbadas y conforman conjuntamente el núcleo de la Zona Metropolitana de Tepic, al este y sur con Santa María del Oro, al sur con Compostela, y; al oeste con San Blas. En este poblado se encuentra la Universidad Tecnológica de Nayarit. Se ubica a 7 km de Tepic y a 739 km de la capital del país la Ciudad de México. ')");
        p1.execSQL("insert into respuestas values('elnayar','El Municipio El Nayar, es uno de los 20 municipios que conforman al estado mexicano de Nayarit, se localiza al oriente del territorio en lo más intrincado de la sierra nayarita, es por superficie el municipio más grande del estado y su cabecera municipal es el pueblo de Jesús María. ','El Nayar Municipality, is one of the 20 municipalities that make up the Mexican state of Nayarit, is located east of the territory in the most intricate of the Sierra Nayarita, is by surface the largest municipality in the state and its municipal seat is the town of Jesús María.')");
        p1.execSQL("insert into respuestas values('rosamorada','Rosamorada, is a municipality of the State of Nayarit. It has an area of \u200B\u200Balmost 2000 Km² and a population of 34,393 inhabitants, showing a gradual decrease since 1980 when the population was 34,695. The majority of its population is rural, the main settlements are Rosamorada with 3,393 inhabitants; Saint Vincent with 4,556;','Rosamorada, es un municipio del Estado de Nayarit. Tiene una superficie de casi 2000 Km² y una población de 34,393 habitantes, mostrando una disminución gradual desde 1980 en que la población era de 34,695. La mayoría de su población es rural, los principales asentamientos son Rosamorada con 3,393 habitantes; San Vicente con 4,556;')");
        p1.execSQL("insert into respuestas values('ruiz','Ruiz, is a municipality of the State of Nayarit, Mexico. It has an area of \u200B\u200B371.3 Km². It limits North with Rosamorada and El Nayar, to the East and South with El Nayar, to the south with Santiago Ixcuintla, and; to the West with the municipality of Tuxpan.','Ruiz, es un municipio del Estado de Nayarit, México. Tiene una superficie de 371.3 Km². Limita al Norte con Rosamorada y El Nayar, al Este y Sur con El Nayar, al sur con Santiago Ixcuintla, y; al Oeste con el municipio de Tuxpan. ')");
        p1.execSQL("insert into respuestas values('sanblas','San Blas, is one of the 20 municipalities of the Mexican state of Nayarit. Its municipal seat is San Blas, a historic port of Mexico.','San Blas, es uno de los 20 municipios del estado mexicano de Nayarit. Su cabecera municipal es San Blas, un puerto histórico de México. ')");
        p1.execSQL("insert into respuestas values('sanpedrolagunillas','San Pedro Lagunillas is a municipality in the State of Nayarit, Mexico.\n" +
                "\n" +
                "It has an area of \u200B\u200B553.66 Km². It limits to the north and northeast with the municipality of Santa María del Oro, to the east and southeast with Ahuacatlán, to the south with the State of Nayarit and to the west and northwest with Compostela.','San Pedro Lagunillas es un municipio del Estado de Nayarit, México.\n" +
                "\n" +
                "Tiene una superficie de 553,66 Km². Limita al norte y noreste con el municipio de Santa María del Oro, al este y sureste con Ahuacatlán, al sur con el Estado de Nayarit y al oeste y noroeste con Compostela. ')");
        p1.execSQL("insert into respuestas values('santamariadeloro','Santa María del Oro, is a municipality of the State of Nayarit, Mexico. It has 1,119.56 km². It limits to the north with the municipality of El Nayar, to the northeast with La Yesca, to the southeast with Jala, to the south with Ahuacatlán, to the west with San Pedro Lagunillas, Xalisco and Compostela; and, to the northwest with Tepic.','Santa María del Oro, es un municipio del Estado de Nayarit, México. Tiene 1,119.56 km². Limita al norte con el municipio de El Nayar, al noreste con La Yesca, al sureste con Jala, al sur con Ahuacatlán, al oeste con San Pedro Lagunillas, Xalisco y Compostela; y, al noroeste con Tepic. ')");
        p1.execSQL("insert into respuestas values('santiagoixcuintla','The Municipality of Santiago Ixcuintla is one of the 20 municipalities in which the State of Nayarit, Mexico is divided.','El Municipio de Santiago Ixcuintla es uno de los 20 municipios en que se encuentra dividido el Estado de Nayarit, México. ')");
        p1.execSQL("insert into respuestas values('tecuala','Tecuala, is a municipality of the State of Nayarit, Mexico. It has an area of \u200B\u200B1,011.06 Km². It limits to the North with the municipality of Acaponeta, to the Northwest with the state of Sinaloa, to the South with Rosamorada and to the Southwest with Santiago Ixcuintla','Tecuala, es un municipio del Estado de Nayarit, México. Tiene una superficie de 1,011.06 Km². Limita al Norte con el municipio de Acaponeta, al Noroeste con el estado de Sinaloa, al Sur con Rosamorada y al Suroeste con Santiago Ixcuintla ')");
        p1.execSQL("insert into respuestas values('tepic','The Municipality of Tepic is one of the 20 municipalities in which the Mexican state of Nayarit is divided; its municipal seat, the city of Tepic, is also the capital of the state.','El Municipio de Tepic es uno de los 20 municipios en que se encuentra dividido el estado mexicano de Nayarit; su cabecera municipal, la ciudad de Tepic, es también la capital del estado. ')");
        p1.execSQL("insert into respuestas values('tuxpan','The municipality of Tuxpan is one of the 20 municipalities in which the Mexican state of Nayarit is divided. Being its municipal head the population of the same name.','El municipio de Tuxpan es uno de los 20 municipios en que se divide el estado mexicano de Nayarit. Siendo su cabecera municipal la población del mismo nombre. ')");
        p1.execSQL("insert into respuestas values('layesca','La Yesca, is a municipality of the State of Nayarit, Mexico. It has an area of \u200B\u200B4,419.86 km². It is bordered to the north by the municipality of El Nayar and the state of Jalisco, to the east by the Zacatecan municipality of Florencia de Benito Juárez and to the south by the state of Jalisco, to the southwest by the municipalities of Santa María del Oro, Jala and Ixtlán. River, to the West with the municipality of El Nayar.','La Yesca, es un municipio del Estado de Nayarit, México. Tiene una superficie de 4,419.86 Km². Limita al Norte con el municipio de El Nayar y el estado de Jalisco, al Este con el municipio zacatecano de Florencia de Benito Juárez y al Sur con el estado de Jalisco, al suroeste con los municipios de Santa María del Oro, Jala e Ixtlán del Río, al Oeste con el municipio de El Nayar. ')");
        p1.execSQL("insert into respuestas values('bahiadebanderas','The Municipality of Bahía de Banderas is one of the 20 municipalities in which the state of Nayarit, Mexico is subdivided; its head is Valle de Banderas. It is located in the South Coast Region of the state. Together with the municipality of Puerto Vallarta in the State of Jalisco, it forms the Metropolitan Area of \u200B\u200BPuerto Vallarta being the second most populated of both states.','El Municipio de Bahía de Banderas es uno de los 20 municipios en que se subdivide el estado de Nayarit, México; su cabecera es Valle de Banderas. Se localiza en la Región Costa Sur del estado. Junto con el municipio de Puerto Vallarta en el Estado de Jalisco, conforma la Zona Metropolitana de Puerto Vallarta siendo así la segunda más poblada de ambos estados. ')");

    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
